coverage:
  precision: 2
  round: down
  range: 60..95

  status:
    project:
      default:
        target: auto
        if_no_uploads: error

    patch:
      default:
        if_no_uploads: error

    changes: true


comment:
  layout: "reach, diff, flags, files"
  behavior: default